import { StyleSheet } from 'react-native'
import { theme } from '@/constants/theme'
export const floatyStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: theme.neutral.bg },
  content: { padding: 16, gap: 16, paddingBottom: 40 },
  subtitle: { fontSize: 13, lineHeight: 20, color: theme.neutral.textSecondary },
  eyebrow: { fontSize: 13, letterSpacing: 0.5, fontWeight: '700', color: theme.neutral.textMuted },
  row: { flexDirection: 'row', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  tabs: { paddingHorizontal: 16, paddingVertical: 10, alignItems: 'center' },
  section: { gap: 12 },
  sectionTitle: { fontSize: 20, fontWeight: '700', color: theme.neutral.textPrimary },
  card: {
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: theme.neutral.border,
    borderRadius: 12,
    backgroundColor: theme.neutral.surfaceDeep,
  },
  label: { fontSize: 15, fontWeight: '600', color: theme.neutral.textPrimary },
  muted: { fontSize: 12, lineHeight: 19, color: theme.neutral.textSecondary },
  error: { fontSize: 13, lineHeight: 20, color: theme.status.error.text },
  success: { fontSize: 13, lineHeight: 20, color: theme.status.success.text },
  banner: {
    marginHorizontal: 18,
    marginBottom: 10,
    padding: 12,
    gap: 8,
    borderRadius: 10,
    backgroundColor: theme.neutral.surfaceDeep,
  },
  empty: { paddingVertical: 28, gap: 10, alignItems: 'flex-start' },
  flex: { flex: 1 },
  map: { flex: 1, minHeight: 220 },
  mapControls: { position: 'absolute', top: 16, left: 12, gap: 8 },
  mapFooter: {
    padding: 16,
    gap: 10,
    backgroundColor: theme.neutral.surfaceDeep,
    borderTopWidth: 1,
    borderColor: theme.neutral.border,
  },
  attribution: { fontSize: 10, color: theme.neutral.textDim },
})
